### ISSUE TITLE
dir_copy needs overwrite argument

### ISSUE THREAD

**Issue by hadley** [r-lib/fs#81] opened 2018-03-02 20:27 UTC

**Comment by jimhester** [comment] 2018-03-09 14:37
Note to self: just need to add `overwrite` argument and  pass `overwrite`  to `file_copy()` and `link_copy()` internally.

**Comment by jdblischak** [comment] 2018-10-23 18:46
@jimhester What's the status on this feature? I was trying to replace a recursive copy of a directory that currently uses `file.copy()` until I realized this wasn't currently possible.

In case it could be useful for testing, here's a reprex of my use case:

``` r
library(fs)
packageVersion("fs")
#> [1] '1.2.6'
dir_create("top1/sub")
cat("old data", file = "top1/sub/1.txt")
cat("old data", file = "top1/sub/2.txt")
dir_create("top2/sub")
cat("new data", file = "top2/sub/1.txt")
cat("new data", file = "top2/sub/2.txt")
cat("new data", file = "top2/sub/3.txt")

dir_copy("top2/sub/", "top1/")
#> Error: [EEXIST] Failed to copy 'top2/sub/1.txt' to 'top1/sub/1.txt': file already exists

file_move("top2/sub/", "top1/")
#> Error: [ENOTEMPTY] Failed to move 'top2/sub'to 'top1/sub': directory not empty

file_copy("top2/sub/", "top1/", overwrite = TRUE)
#> Error: [EISDIR] Failed to copy 'top2/sub' to 'top1/sub': illegal operation on a directory

file.copy("top2/sub/", "top1/", overwrite = TRUE, recursive = TRUE)
#> [1] TRUE
```

<sup>Created on 2018-10-23 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

**Comment by pasipasi123** [comment] 2019-04-16 12:34
Like this? `overwrite` needs to be checked in the `if` statement because the default behavior is to create a new directory under `new_path`. 

```
dir_copy <- function (path, new_path, overwrite = FALSE) 
{
  assert_no_missing(path)
  assert_no_missing(new_path)
  assert("`path` must be a directory", all(is_dir(path)))
  assert("Length of `path` must equal length of `new_path`",
         length(path) == length(new_path))
  for (i in seq_along(path)) {
    if (isFALSE(overwrite) & isTRUE(unname(is_dir(new_path[[i]])))) {
      new_path[[i]] <- path(new_path[[i]], path_file(path))
    }
    dir_create(new_path[[i]])
    dirs <- dir_ls(path[[i]], type = "directory", recursive = TRUE, 
                   all = TRUE)
    dir_create(path(new_path[[i]], path_rel(dirs, path[[i]])))
    files <- dir_ls(path, recursive = TRUE, type = c("unknown", 
                                                     "file", "FIFO", "socket", "character_device", "block_device"), 
                    all = TRUE)
    file_copy(files, path(new_path[[i]], path_rel(files, 
                                                  path[[i]])), overwrite = overwrite)
    links <- dir_ls(path, recursive = TRUE, type = "symlink", 
                    all = TRUE)
    link_copy(links, path(new_path[[i]], path_rel(links, 
                                                  path[[i]])), overwrite = overwrite)
  }
  invisible(path_tidy(new_path))
}

```

**Comment by jimhester** [comment] 2019-04-16 17:17
Last time I looked at it I couldn't find an implementation I liked. @pasipasi123 that looks like a good start, if you are up for it could you open a PR with it and add some tests with some of the examples @jdblischak showed we can review it there.

**Comment by jdblischak** [comment] 2019-04-16 17:40
And I can help with writing the unit tests and/or trying out the new implementation. Just let me know!

**Comment by pasipasi123** [comment] 2019-04-19 14:06
I've added a PR with the overwrite argument and also one simple test.

**Comment by jimhester** [comment] 2019-04-19 15:25
@jdblischak In your example what result are you expecting? @pasipasi123's implementation gives you a different result then using `file.copy()`. Were you expecting the first or the second from below?

``` r
library(fs)
create_trees <- function() {
  dir_create("top1/sub")
  cat("old data", file = "top1/sub/1.txt")
  cat("old data", file = "top1/sub/2.txt")
  dir_create("top2/sub")
  cat("new data", file = "top2/sub/1.txt")
  cat("new data", file = "top2/sub/2.txt")
  cat("new data", file = "top2/sub/3.txt")
}

create_trees()
file.copy("top2/sub/", "top1/", overwrite = TRUE, recursive = TRUE)
#> [1] TRUE
dir_tree("top1")
#> top1
#> └── sub
#>     ├── 1.txt
#>     ├── 2.txt
#>     └── 3.txt

dir_delete(c("top1", "top2"))

create_trees()
dir_copy("top2/sub/", "top1/", overwrite = TRUE)
dir_tree("top1")
#> top1
#> ├── 1.txt
#> ├── 2.txt
#> ├── 3.txt
#> └── sub
#>     ├── 1.txt
#>     └── 2.txt

dir_delete(c("top1", "top2"))
```

<sup>Created on 2019-04-19 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by jdblischak** [comment] 2019-04-19 15:44
I expect the behavior of `file.copy()`. I need a convenient way to update outdated files in one subdirectory with the updated files in another subdirectory, even if these subdirectories have the same name (i.e. only their full path differs).

And in the second form above, no files were overwritten. It was a recursive copy of the files in `top2/sub/` to `top1/`. In contrast, I want to copy the directory `sub` from `top2` to `top1`. To instead copy all the files in a directory like the current example, I think `file_copy()` should be used in combination with `dir_ls()`.

Does my use case make sense?

**Comment by pasipasi123** [comment] 2019-04-19 16:14
In my implementation `new_path` should be `top1/sub/` to work like `file.copy` does. This allows you to change the directory name as well as keeping it the same.

``` r
library(fs)
create_trees <- function() {
  dir_create("top1/sub")
  cat("old data", file = "top1/sub/1.txt")
  cat("old data", file = "top1/sub/2.txt")
  dir_create("top2/sub")
  cat("new data", file = "top2/sub/1.txt")
  cat("new data", file = "top2/sub/2.txt")
  cat("new data", file = "top2/sub/3.txt")
}

create_trees()
file.copy("top2/sub/", "top1/", overwrite = TRUE, recursive = TRUE)
#> [1] TRUE
dir_tree("top1")
#> top1
#> \-- sub
#>     +-- 1.txt
#>     +-- 2.txt
#>     \-- 3.txt


dir_delete(c("top1", "top2"))

create_trees()
dir_copy("top2/sub/", "top1/sub/", overwrite = TRUE)
dir_tree("top1")
#> top1
#> \-- sub
#>     +-- 1.txt
#>     +-- 2.txt
#>     \-- 3.txt


dir_delete(c("top1", "top2"))
```

<sup>Created on 2019-04-19 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by jdblischak** [comment] 2019-04-19 16:32
> In my implementation new_path should be top1/sub/ to work like file.copy does.

I'd be fine with this behavior as long as it is documented. Basically, `new_path` will always become the new name of the directory (instead of copying the directory with its current name into the new path).

Thus the first call below will copy all the files, but the second will actually create a new subdirectory `b/` downstream of `c/d/`:

```
# Copy all the files in a/b/ into c/d/, overwriting any that already exist
dir_copy("a/b/", "c/d/", overwrite = TRUE)
# Copy all the files in a/b/ into c/d/b/
dir_copy("a/b/", "c/d/b/")
```

Do I understand the intended behavior correctly?

**Comment by pasipasi123** [comment] 2019-04-20 09:49
Yes. When `overwrite = FALSE` the behavior is exactly the same as in the CRAN version right now. There's a slight twist though: the result of `dir_copy("a/b/", "c/d/b")` depends on the existence of directory `b` under `c/d/`. 

``` r
library(fs)

dir_create("a/b/")
dir_copy("a/b/", "c/d/b/")
dir_tree("c")
#> c
#> \-- d
#>     \-- b

dir_copy("a/b/", "c/d/b/")
dir_tree("c")
#> c
#> \-- d
#>     \-- b
#>         \-- b

dir_delete(c("a", "c"))
```

<sup>Created on 2019-04-20 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by pasipasi123** [comment] 2019-04-20 14:19
BTW, `file.copy` and `file.create` are not safe to use. Because `file.copy` allows you to not specify the `to` directory name (here directory `sub` is created under `top1` `file.copy("top2/sub/", "top1/", overwrite = TRUE, recursive = TRUE)`), you can accidentally delete your files.

The problem with these base functions are that `file.copy` doesn't check if `from` and `to` are actually the same and `file.create` does not check if the file already exists.

``` r
library(fs)

file_create("foo")
cat("bar\n", file = "foo")
file.copy("foo", ".", recursive = TRUE)
#> [1] TRUE
readLines("foo")
#> character(0)

cat("bar\n", file = "foo")
file.create("foo")
#> [1] TRUE
readLines("foo")
#> character(0)

file_delete("foo")
```

<sup>Created on 2019-04-20 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by jimhester** [comment] 2019-05-02 12:22
@pasipasi123 that looks like the same behavior as using `cp -r`, which is what we want, so that is good.

```shell
> mkdir -p a/b
> mkdir -p c/d
> cp -r a/b c/d/b
> tree c
c
└── d
    └── b

2 directories, 0 files
> rm -r c
> mkdir -p c/d/b
> cp -r a/b c/d/b
> tree c
c
└── d
    └── b
        └── b

3 directories, 0 files
```

**Closed** 2019-05-02 12:34 UTC
Labels: bug, feature
