### ISSUE TITLE
dir_create() alters umask

### ISSUE THREAD

**Issue by wch** [r-lib/fs#293] opened 2020-09-10 20:29 UTC
Example:

```R
Sys.umask()
#> [1] "22"
fs::dir_create('foo')
Sys.umask()
#> [1] "0"
```

Any files created after this point will be world readable and writable. For example:

```R
writeLines('abc', 'temp.txt')
file.mode('temp.txt')
#> [1] "666"
```

**Comment by jimhester** [comment] 2020-09-11 13:05
Is this a duplicate of https://github.com/r-lib/fs/issues/284?

**Comment by wch** [comment] 2020-09-11 13:09
I think it was created by the fix for that issue, and the problem is this line:
https://github.com/r-lib/fs/blob/93e70a93c00946791945c63ab9e9863ed8f3e1cf/src/dir.cc#L18

**Comment by jimhester** [comment] 2020-09-11 13:10
Yeah I see the issue from the man page now https://man7.org/linux/man-pages/man2/umask.2.html

> It is impossible to use umask() to fetch a process's umask without at
       the same time changing it.  A second call to umask() would then be
       needed to restore the umask.

So we need to reset it after the fact.

**Comment by wch** [comment] 2020-09-11 13:13
That's such a weird interface, and it sounds like it could cause problems when there are multiple threads.

**Comment by jimhester** [comment] 2020-09-11 13:23
Yes I agree, but I don't think there is any other way we can do it. I tweaked when we do this and added a test in 857a814ad15f

**Closed by jimhester** 2020-09-11 13:23 UTC

**Comment by wch** [comment] 2020-09-11 13:44
Sorry to keep pressing on this, but as long as the global umask is being altered, I think it would be safer to:
* Call `umask()` with a more restrictive value (instead of less restrictive)
* Immediately set it back to the original value
* Call `chmod` on the directory after creating it

The way things currently work, if there's a networked filesystem, the time between the two `umask()` calls could be significant, and it would be best to be as safe as possible.

**Comment by jimhester** [comment] 2020-09-11 14:12
If we are calling chmod then we might as well forget about umask entirely.

**Comment by wch** [comment] 2020-09-11 14:30
I was thinking you'd still set the `mode` based on `INTEGER(mode_sxp)[0] & ~process_umask`. 

I figured the umask stuff was there so you would respect the process umask (and not just set the permissions to whatever the user has requested) but I might not be fully understanding how this all works.
