### ISSUE TITLE
install of fs-1.2.6 fails on Power8 IBM system

### ISSUE THREAD

**Issue by CNKb80Q3** [r-lib/fs#163] opened 2019-01-05 19:11 UTC

**Comment by xbeta** [comment] 2019-01-11 23:54
I faced similar problem with macOS Mojave (10.14.2)

**Comment by commandline-be** [comment] 2019-01-15 06:43
Just a guess but a short search shows 'pthread_atfork' is part of the POSIX standard. A workaround may be to check if there are more up to date libc or additional libraries or similar available ?

This thread may well offer a fix https://community.rstudio.com/t/shiny-installation-fails-with-undefined-symbol-pthread-atfork/7647

**Comment by CNKb80Q3** [comment] 2019-01-15 18:20
After applying the latest update to the libc-bin, libc-dev-bin for Ubuntu 16.04.1 ppc64el, the same problem remained alive and well on attempting to install devtools, which requires fs as a depedency. I will explore the other suggestions provided so far.

**Comment by commandline-be** [comment] 2019-01-15 19:47
i tried installing devtools for a different reason and noticed it brings fs, this is not a solution.

the core issue here is `fs.so: undefined symbol: pthread_atfork` which appears to be caused by outdated software in the fs package. 

the output line `Error: package or namespace load failed for ‘fs’ in dyn.load(file, DLLpath = DLLpath, ...):
unable to load shared object '/gpfs/software/R351/lib64/R/library/fs/libs/fs.so':
/gpfs/software/R351/lib64/R/library/fs/libs/fs.so: undefined symbol: pthread_atfork`

try running `R CMD ldd /gpfs/software/R351/lib64/R/library/fs/libs/fs.so`

Also, while installing the package files are usually unpacked under a `/tmp` directory usually shown below the line `The downloaded source packages are in`

As a matter of thinking out loud ... given the plethora of open issues with installing fs i'm concerned this is poor quality or poorly maintained software, still, many packages depend on it so it must have some merit or it is the only one of the kind out there. Then again, i'm new to R, it may be i messed up the environment.

**Comment by jimhester** [comment] 2019-02-11 21:16
This is already fixed in the development version of fs, it will be on CRAN at some point in the future.

**Closed by jimhester** 2019-02-11 21:16 UTC

**Comment by CNKb80Q3** [comment] 2019-03-18 15:36
Am I correct in interpreting this to mean that I will need to wait for fs-1.2.x, x>6, to appear on CRAN before I can test the fix for getting a successful fs installation when it is called for during the devtools install in the IBM Power8 ubuntu 16.04.1 environment?

Bill
