### ISSUE TITLE
Segfault when calling `path_home()` 

### ISSUE THREAD

**Issue by kevinushey** [r-lib/fs#58] opened 2018-01-31 21:34 UTC
Some users at rstudio::conf were encountering segfaults when attempting to call `path_home()`. In fact, the error occurred while attempting to print the path -- unfortunately I don't have the call stack but the process was dying within a call to the `stat_` R function with a null pointer dereference.

One user who encountered this was using El Capitan, in case the use of an older toolchain could be an issue.

**Comment by jimhester** [comment] 2018-02-21 15:31
This is likely from the same cause as the build failures on CRAN MacOS builder
https://www.r-project.org/nosvn/R.check/r-release-osx-x86_64/fs-00check.html

Unfortunately I am still unable to reproduce this to figure out the issue

**Comment by jimhester** [comment] 2018-03-12 20:22
Should be fixed by https://github.com/r-lib/fs/commit/901cb50fc2f4d25bb8b920514f52574be42d7aa5

**Closed by jimhester** 2018-03-12 20:22 UTC
Labels: bug
